### PR TITLE
feat: add reactions block

### LINKED ISSUE #31: Reactions Block
@chrisbellboy please add summary details for reactions block here.

### PR DESCRIPTION
**Pull request by chrisbellboy**
#### Changes proposed in this Pull Request

* Adds a Reactions block. 

The readme.txt has an overview of the options and includes examples for styling the block. It [can also be seen running here](https://staging-1e4a-stevejurvetsonphotos.wpcomstaging.com/note/).

CC @dhanson-wp

### CODE REVIEW

**Review by nate-allen — CHANGES_REQUESTED** [review]
Hi @chrisbellboy! Overall the code looks really good. Unfortunately though it didn't work when I tested it because the `wpcomsp_reactions` custom table never gets created. I think it would make sense to do that in the `wpcomsp_reactions_block_init` function. Have it check if the table exists and create it if not. We would need to make sure that it's done in a way that is going to scale though, so just keep that in mind.

**Comment by nate-allen** [comment]
@chrisbellboy Wanted to make sure you saw [this review](https://github.com/a8cteam51/special-projects-blocks-monorepo/pull/33#pullrequestreview-2421525263). It doesn't look like your recent changes address it, unless I'm missing something.

**Comment by chrisbellboy** [comment]
Hey @nate-allen Sorry for the super slow response, those other pushes were addressing a separate issue I spotted on Steve's site!

Re: table not getting created - ah I think I know why that may be. Did you test it via the monorepo plugin? Because if so, then that would be why. The reactions plugin currently uses `register_activation_hook` ([in this file](https://github.com/a8cteam51/special-projects-blocks-monorepo/blob/c360a916daf2adf5638fac0bff030c272d5e88c3/reactions/reactions.php#L25)) to create the table, but the caveat is that this hook only fires when called from a file at the root level of a plugin.

In the monorepo setup, since reactions.php is located in a subdirectory, the hook doesn’t ever fire! However, when the reactions plugin is installed as a normal standalone plugin, the table should be created without issue.

I did run into this at one point when testing the monorepo and it had me stumped for a while until I learnt about it having to be in a root file. To account for monorepo users (and for sites that accidentally delete the table), I did also add a fallback notice that should appear if the table doesn’t exist, along with a button to create it manually. Did you happen to see that during testing?

With all that in mind, I’m happy to move the logic to the init hook if you still think it’s a better fit - as it would prevent any monorepo devs needing to create it via the fallback notice. The only tradeoff I see is that it would add a minor extra database check on every page load, although admittedly it would be negligible performance-wise. Could also move it to an admin hook so it only fires on admin page loads?

Let me know either way and I'll work on the changes 👍

**Comment by chrisbellboy** [comment]
And also thanks for reviewing! 👍

**Review by nate-allen — APPROVED** [review]

**Pull request merged**
